// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Keyless]
    [Table("A_DiagnosticLogCategories")]
    public partial class ADiagnosticLogCategories
    {
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string Cloud { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string ResourceProviderType { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string Category { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string CategoryDisplayName { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Approved { get; set; }
    }
}