// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Keyless]
    [Table("AllRTMetricsLogsStatus")]
    [Index("Cloud", "ResourceProviderTypeMetrics", "ResourceProviderTypeLogs", Name = "Idx_AllRTMetricsLogsStatus")]
    public partial class AllRtmetricsLogsStatus
    {
        [Required]
        [StringLength(50)]
        public string Cloud { get; set; }
        [Column("ResourceProviderType_Metrics")]
        [StringLength(200)]
        public string ResourceProviderTypeMetrics { get; set; }
        [Column("Has_Metrics")]
        public int? HasMetrics { get; set; }
        [Column("ResourceProviderType_Logs")]
        [StringLength(200)]
        public string ResourceProviderTypeLogs { get; set; }
        [Column("Has_Logs")]
        public int? HasLogs { get; set; }
    }
}