// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Keyless]
    [Table("AllRTLogsStatus")]
    [Index("Cloud", "ResourceProviderType", Name = "Idx_AllRTLogsStatus")]
    public partial class AllRtlogsStatus
    {
        [Required]
        [StringLength(50)]
        public string Cloud { get; set; }
        [Required]
        [StringLength(200)]
        public string ResourceProviderType { get; set; }
        [Column("Has_Logs")]
        public int? HasLogs { get; set; }
        public int? Type { get; set; }
    }
}