// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Keyless]
    [Table("AllRTMetricsLogsStatus_Unified")]
    [Index("Cloud", "ResourceProviderType", Name = "Idx_AllRTMetricsLogsStatus_Unified")]
    public partial class AllRtmetricsLogsStatusUnified
    {
        [Required]
        [StringLength(50)]
        public string Cloud { get; set; }
        [StringLength(100)]
        public string ResourceProvider { get; set; }
        [StringLength(200)]
        public string ResourceType { get; set; }
        [Required]
        [StringLength(200)]
        public string ResourceProviderType { get; set; }
        public int? Class { get; set; }
        [Column("Has_Metrics")]
        public int? HasMetrics { get; set; }
        [Column("Type_Metrics")]
        public int? TypeMetrics { get; set; }
        [Column("Has_Logs")]
        public int? HasLogs { get; set; }
        [Column("Type_Logs")]
        public int? TypeLogs { get; set; }
        [Column("TypeDesc_Metrics")]
        [StringLength(50)]
        [Unicode(false)]
        public string TypeDescMetrics { get; set; }
        [Column("TypeDesc_Logs")]
        [StringLength(50)]
        [Unicode(false)]
        public string TypeDescLogs { get; set; }
        [Column("ServiceID")]
        [StringLength(100)]
        public string ServiceId { get; set; }
        [StringLength(150)]
        public string ServiceRing { get; set; }
        [Column("routingType")]
        [StringLength(100)]
        public string RoutingType { get; set; }
    }
}