// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Keyless]
    [Table("A_metricPerResourceType")]
    public partial class AMetricPerResourceType
    {
        [Required]
        [Unicode(false)]
        public string Cloud { get; set; }
        [Required]
        [Unicode(false)]
        public string ResourceProviderType { get; set; }
        [Required]
        [Unicode(false)]
        public string Metric { get; set; }
        [Required]
        [Unicode(false)]
        public string MetricDisplayName { get; set; }
        [Required]
        [Unicode(false)]
        public string Unit { get; set; }
        [Required]
        [Unicode(false)]
        public string AggregationType { get; set; }
        [Unicode(false)]
        public string Description { get; set; }
        [Required]
        [Unicode(false)]
        public string Dimensions { get; set; }
        [Column("MDMAccount")]
        [Unicode(false)]
        public string Mdmaccount { get; set; }
        [Column("MDMNameSpace")]
        [Unicode(false)]
        public string MdmnameSpace { get; set; }
        [Unicode(false)]
        public string SupportedTimeGrainTypes { get; set; }
        public byte Approved { get; set; }
        public bool Exportable { get; set; }
        [Unicode(false)]
        public string LockAggregationType { get; set; }
        [Required]
        [Unicode(false)]
        public string IsInternal { get; set; }
        public DateTime DateUpdated { get; set; }
    }
}