// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Keyless]
    [Table("Change_Logs")]
    [Index("Cloud", "ResourceProviderTypeTotal", "CategoryTotal", Name = "Idx_Change_Logs")]
    public partial class ChangeLogs
    {
        [Required]
        [StringLength(50)]
        public string Cloud { get; set; }
        [Required]
        [Column("ResourceProviderType_Total")]
        [StringLength(200)]
        public string ResourceProviderTypeTotal { get; set; }
        [Required]
        [Column("Category_Total")]
        [StringLength(100)]
        public string CategoryTotal { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string ChangeType { get; set; }
        public int ChangeTypeNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ProcessDate { get; set; }
        [Column("Change_CategoryDisplayName")]
        public int ChangeCategoryDisplayName { get; set; }
        [Column("ResourceProviderType_Current")]
        [StringLength(200)]
        public string ResourceProviderTypeCurrent { get; set; }
        [Column("ResourceProviderType_Pre")]
        [StringLength(200)]
        public string ResourceProviderTypePre { get; set; }
        [Column("Category_Current")]
        [StringLength(100)]
        public string CategoryCurrent { get; set; }
        [Column("Category_Pre")]
        [StringLength(100)]
        public string CategoryPre { get; set; }
        [Column("CategoryDisplayName_Current")]
        [StringLength(150)]
        public string CategoryDisplayNameCurrent { get; set; }
        [Column("CategoryDisplayName_Pre")]
        [StringLength(150)]
        public string CategoryDisplayNamePre { get; set; }
    }
}