// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Table("Change_Logs_Historical_ACROSS_Clouds_NAMM")]
    public partial class ChangeLogsHistoricalAcrossCloudsNamm
    {
        [Key]
        [StringLength(50)]
        public string Cloud { get; set; }
        [Key]
        [Column("ResourceProviderType_Total")]
        [StringLength(200)]
        public string ResourceProviderTypeTotal { get; set; }
        [Key]
        [Column("Category_Total")]
        [StringLength(100)]
        public string CategoryTotal { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string ChangeType { get; set; }
        public int ChangeTypeNumber { get; set; }
        [Key]
        [Column(TypeName = "datetime")]
        public DateTime ProcessDate { get; set; }
        [Column("Change_CategoryDisplayName")]
        public int ChangeCategoryDisplayName { get; set; }
        [Column("ResourceProviderType_Master")]
        [StringLength(200)]
        public string ResourceProviderTypeMaster { get; set; }
        [Column("ResourceProviderType_Selected")]
        [StringLength(200)]
        public string ResourceProviderTypeSelected { get; set; }
        [Column("Category_Master")]
        [StringLength(100)]
        public string CategoryMaster { get; set; }
        [Column("Category_Selected")]
        [StringLength(100)]
        public string CategorySelected { get; set; }
        [Column("CategoryDisplayName_Master")]
        [StringLength(150)]
        public string CategoryDisplayNameMaster { get; set; }
        [Column("CategoryDisplayName_Selected")]
        [StringLength(150)]
        public string CategoryDisplayNameSelected { get; set; }
    }
}