// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    public partial class Cloud
    {
        [Key]
        [Column("Cloud")]
        [StringLength(50)]
        public string Cloud1 { get; set; }
        [StringLength(50)]
        public string Description { get; set; }
    }
}