// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Keyless]
    [Table("CosmosDBCaseResults", Schema = "IcM")]
    public partial class CosmosDbcaseResults
    {
        [Column("resourceType")]
        [StringLength(200)]
        public string ResourceType { get; set; }
        [Column("account")]
        [StringLength(200)]
        public string Account { get; set; }
        [Column("metricNamespace")]
        [StringLength(200)]
        public string MetricNamespace { get; set; }
        [Column("metricName")]
        [StringLength(200)]
        public string MetricName { get; set; }
        [Column("reason")]
        [StringLength(200)]
        public string Reason { get; set; }
    }
}