// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Keyless]
    [Table("Dashboard_NAMM")]
    public partial class DashboardNamm
    {
        [Column(TypeName = "datetime")]
        public DateTime? ProcessDate { get; set; }
        [StringLength(50)]
        public string Cloud { get; set; }
        [Column("NumberMetrics_Enabled")]
        public int? NumberMetricsEnabled { get; set; }
        [Column("NumberMetrics_NotEnabled")]
        public int? NumberMetricsNotEnabled { get; set; }
        [Column("NumberLogs_Enabled")]
        public int? NumberLogsEnabled { get; set; }
        [Column("NumberLogs_NotEnabled")]
        public int? NumberLogsNotEnabled { get; set; }
        [Column("Number_RTs_OkFile")]
        public int? NumberRtsOkFile { get; set; }
        [Column("Number_RTs_ErrorFile")]
        public int? NumberRtsErrorFile { get; set; }
        public int? MetricsY { get; set; }
        public int? MetricsN { get; set; }
        public int? LogsY { get; set; }
        public int? LogsN { get; set; }
        [Column("Changes_WithinCloud_Total_Metrics")]
        public int? ChangesWithinCloudTotalMetrics { get; set; }
        [Column("Changes_WithinCloud_Add_Metrics")]
        public int? ChangesWithinCloudAddMetrics { get; set; }
        [Column("Changes_WithinCloud_Remove_Metrics")]
        public int? ChangesWithinCloudRemoveMetrics { get; set; }
        [Column("Changes_WithinCloud_Update_Metrics")]
        public int? ChangesWithinCloudUpdateMetrics { get; set; }
        [Column("Changes_WithinCloud_Total_Logs")]
        public int? ChangesWithinCloudTotalLogs { get; set; }
        [Column("Changes_WithinCloud_Add_Logs")]
        public int? ChangesWithinCloudAddLogs { get; set; }
        [Column("Changes_WithinCloud_Remove_Logs")]
        public int? ChangesWithinCloudRemoveLogs { get; set; }
        [Column("Changes_WithinCloud_Update_Logs")]
        public int? ChangesWithinCloudUpdateLogs { get; set; }
        [Column("Changes_AcrossCloud_Total_Metrics")]
        public int? ChangesAcrossCloudTotalMetrics { get; set; }
        [Column("Changes_AcrossCloud_MS_Metrics")]
        public int? ChangesAcrossCloudMsMetrics { get; set; }
        [Column("Changes_AcrossCloud_SM_Metrics")]
        public int? ChangesAcrossCloudSmMetrics { get; set; }
        [Column("Changes_AcrossCloud_MnS_Metrics")]
        public int? ChangesAcrossCloudMnSMetrics { get; set; }
        [Column("Changes_AcrossCloud_Total_Logs")]
        public int? ChangesAcrossCloudTotalLogs { get; set; }
        [Column("Changes_AcrossCloud_MS_Logs")]
        public int? ChangesAcrossCloudMsLogs { get; set; }
        [Column("Changes_AcrossCloud_SM_Logs")]
        public int? ChangesAcrossCloudSmLogs { get; set; }
        [Column("Changes_AcrossCloud_MnS_Logs")]
        public int? ChangesAcrossCloudMnSLogs { get; set; }
    }
}