// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Keyless]
    [Table("Dashboard_IcM", Schema = "IcM")]
    public partial class DashboardIcM
    {
        [Column(TypeName = "datetime")]
        public DateTime? ProcessDate { get; set; }
        [Column("Source_ID")]
        [StringLength(7)]
        public string SourceId { get; set; }
        [Column("Number_Incidents")]
        public int? NumberIncidents { get; set; }
        [Column("Number_Incident_Details")]
        public int? NumberIncidentDetails { get; set; }
    }
}