// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Keyless]
    [Table("DiagnosticLogCategories_Previous_NAMM")]
    [Index("Cloud", "ResourceProviderType", Name = "Idx_DiagnosticLogCategories_Previous_NAMM")]
    public partial class DiagnosticLogCategoriesPreviousNamm
    {
        [Required]
        [StringLength(50)]
        public string Cloud { get; set; }
        [Required]
        [StringLength(200)]
        public string ResourceProviderType { get; set; }
        [StringLength(100)]
        public string Category { get; set; }
        [StringLength(150)]
        public string CategoryDisplayName { get; set; }
        public int? Approved { get; set; }
        [Column("logsEnabled")]
        public int? LogsEnabled { get; set; }
        public int? CostsToExport { get; set; }
    }
}