// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Table("Incident_Detail", Schema = "IcM")]
    public partial class IncidentDetail
    {
        [Key]
        [StringLength(7)]
        public string Source { get; set; }
        [Key]
        [StringLength(200)]
        public string ResourceType { get; set; }
        [Key]
        public int ErrorType { get; set; }
        [Key]
        public int Week { get; set; }
        [Key]
        [Column("IcMIncidentID")]
        public int IcMincidentId { get; set; }
        [Key]
        [StringLength(237)]
        public string Value { get; set; }
        [Column("DateCreated_DB", TypeName = "datetime")]
        public DateTime? DateCreatedDb { get; set; }
        [Column("DateCreated_IcM", TypeName = "datetime")]
        public DateTime? DateCreatedIcM { get; set; }
        public string Description { get; set; }
    }
}