// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Table("Incident", Schema = "IcM")]
    public partial class Incident
    {
        [Key]
        [StringLength(7)]
        public string Source { get; set; }
        [Key]
        [StringLength(200)]
        public string ResourceType { get; set; }
        [Key]
        public int ErrorType { get; set; }
        [Key]
        public int Week { get; set; }
        [Key]
        [Column("IcMIncidentID")]
        public int IcMincidentId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime WeekStart { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime WeekEnd { get; set; }
        [StringLength(100)]
        public string ResourceProvider { get; set; }
        [Column("DateCreated_DB", TypeName = "datetime")]
        public DateTime? DateCreatedDb { get; set; }
        [Column("DateCreated_IcM", TypeName = "datetime")]
        public DateTime? DateCreatedIcM { get; set; }
        public int? OperationStatus { get; set; }
        public int? Severity { get; set; }
        [StringLength(200)]
        public string ProposedOwningService { get; set; }
        [StringLength(200)]
        public string ProposedOwningTeam { get; set; }
        [Column("IcMLandedService")]
        [StringLength(200)]
        public string IcMlandedService { get; set; }
        [Column("IcMLandedTeam")]
        [StringLength(200)]
        public string IcMlandedTeam { get; set; }
        [StringLength(300)]
        public string LinkToIcM { get; set; }
    }
}