// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Table("Manifest_Management")]
    public partial class ManifestManagement
    {
        [Key]
        [StringLength(150)]
        public string ResourceProvider { get; set; }
        [Key]
        [Column("ResourceTypeNoRP")]
        [StringLength(150)]
        public string ResourceTypeNoRp { get; set; }
        [Column("incidentRoutingService")]
        [StringLength(500)]
        public string IncidentRoutingService { get; set; }
        [Column("incidentRoutingTeam")]
        [StringLength(500)]
        public string IncidentRoutingTeam { get; set; }
        [Column("incidentContactEmail")]
        [StringLength(500)]
        public string IncidentContactEmail { get; set; }
        [Column("resourceAccessPolicy")]
        [StringLength(500)]
        public string ResourceAccessPolicy { get; set; }
    }
}