// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Table("Manifest_RT")]
    public partial class ManifestRt
    {
        [Key]
        [StringLength(150)]
        public string ResourceProvider { get; set; }
        [Key]
        [Column("ResourceTypeNoRP")]
        [StringLength(150)]
        public string ResourceTypeNoRp { get; set; }
        [Column("routingType")]
        [StringLength(500)]
        public string RoutingType { get; set; }
    }
}