// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Table("Manifest_RP")]
    public partial class ManifestRp
    {
        [Key]
        [StringLength(100)]
        public string ResourceProvider { get; set; }
        [Column("Has_PROD")]
        public int? HasProd { get; set; }
        [Column("Has_JSON")]
        public int? HasJson { get; set; }
        [Column("namespace")]
        [StringLength(200)]
        public string Namespace { get; set; }
        [Column("providerVersion")]
        [StringLength(100)]
        public string ProviderVersion { get; set; }
        [Column("providerType")]
        [StringLength(500)]
        public string ProviderType { get; set; }
    }
}