// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Table("MetricsLogs_PersistentParameters")]
    public partial class MetricsLogsPersistentParameters
    {
        [Key]
        [StringLength(50)]
        public string Cloud { get; set; }
        [Key]
        [StringLength(200)]
        public string ResourceProviderType { get; set; }
        [Key]
        [StringLength(100)]
        public string MetricLog { get; set; }
        [Key]
        [StringLength(1)]
        public string Type { get; set; }
        public int? Approved { get; set; }
        public int? CostsToExport { get; set; }
    }
}