// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Keyless]
    [Table("MetricsPerResourceType_Previous")]
    [Index("Cloud", "ResourceProviderType", Name = "Idx_MetricsPerResourceType_Previous")]
    public partial class MetricsPerResourceTypePrevious
    {
        [Required]
        [StringLength(50)]
        public string Cloud { get; set; }
        [Required]
        [StringLength(200)]
        public string ResourceProviderType { get; set; }
        [StringLength(100)]
        public string Metric { get; set; }
        [StringLength(150)]
        public string MetricDisplayName { get; set; }
        [StringLength(25)]
        public string Unit { get; set; }
        [StringLength(25)]
        public string AggregationType { get; set; }
        [StringLength(1200)]
        public string Description { get; set; }
        [StringLength(300)]
        public string Dimensions { get; set; }
        [Column("MDMAccount")]
        [StringLength(100)]
        public string Mdmaccount { get; set; }
        [Column("MDMNameSpace")]
        [StringLength(100)]
        public string MdmnameSpace { get; set; }
        [StringLength(200)]
        public string SupportedTimeGrainTypes { get; set; }
        public int? Approved { get; set; }
        public int? Exportable { get; set; }
        [StringLength(50)]
        public string LockAggregationType { get; set; }
        public int? CostsToExport { get; set; }
    }
}