// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Table("NAMM_RT")]
    public partial class NammRt
    {
        [Key]
        [StringLength(50)]
        public string Cloud { get; set; }
        [Required]
        [StringLength(100)]
        public string ResourceProvider { get; set; }
        [Key]
        [StringLength(200)]
        public string ResourceType { get; set; }
        [Column("displayName")]
        [StringLength(200)]
        public string DisplayName { get; set; }
        [Column("serviceTreeId")]
        [StringLength(100)]
        public string ServiceTreeId { get; set; }
        [Column("logsEnabled")]
        public int? LogsEnabled { get; set; }
        [Column("metricsEnabled")]
        public int? MetricsEnabled { get; set; }
        [Column("ServiceID")]
        [StringLength(100)]
        public string ServiceId { get; set; }
        [StringLength(150)]
        public string ServiceRing { get; set; }
        [Column("routingType")]
        [StringLength(100)]
        public string RoutingType { get; set; }
        [Column("incidentRoutingService")]
        [StringLength(150)]
        public string IncidentRoutingService { get; set; }
        [Column("incidentRoutingTeam")]
        [StringLength(150)]
        public string IncidentRoutingTeam { get; set; }
    }
}