// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Table("NAMM_RPRT")]
    public partial class NammRprt
    {
        [Key]
        [StringLength(50)]
        public string Cloud { get; set; }
        [Key]
        [StringLength(100)]
        public string ResourceProvider { get; set; }
        [Key]
        [StringLength(200)]
        public string ResourceType { get; set; }
        [StringLength(50)]
        public string ProcessStatus { get; set; }
    }
}