// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Table("OperationStatus", Schema = "IcM")]
    public partial class OperationStatus
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
    }
}