// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CloudManifestServices.Models
{
    [Table("Process_Control")]
    public partial class ProcessControl
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(500)]
        public string ControlPointDescription { get; set; }
        [StringLength(500)]
        public string Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ProcessDate { get; set; }
    }
}